"""add trip participant status

Revision ID: 5ce1d4289bce
Revises: 
Create Date: 2026-01-17 17:37:42.513350+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce1d4289bce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('avatar_configs')
    
    with op.batch_alter_table('map_members', schema=None) as batch_op:
        batch_op.alter_column('color',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.String(length=20),
                   nullable=False,
                   server_default='#3B82F6')
        batch_op.drop_column('marker_color')

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.alter_column('is_public',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   nullable=False,
                   existing_server_default=sa.text('0'))

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('creator_color',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=20),
                   nullable=False,
                   server_default='blue')

    with op.batch_alter_table('trip_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='invited'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_participants', schema=None) as batch_op:
        batch_op.drop_column('status')
    
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('creator_color',
                   existing_type=sa.String(length=20),
                   type_=sa.TEXT(),
                   nullable=True,
                   existing_server_default=sa.text('("blue")'))

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.alter_column('is_public',
                   existing_type=sa.Boolean(),
                   type_=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('0'))

    with op.batch_alter_table('map_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marker_color', sa.TEXT(), server_default=sa.text('("blue")'), nullable=True))
        batch_op.alter_column('color',
                   existing_type=sa.String(length=20),
                   type_=sa.VARCHAR(length=7),
                   nullable=True,
                   existing_server_default=sa.text("'#3B82F6'"))

    op.create_table('avatar_configs',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('hair_style', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=7), nullable=False),
    sa.Column('body_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('face_shape', sa.VARCHAR(length=50), nullable=False),
    sa.Column('eye_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=7), nullable=False),
    sa.Column('skin_tone', sa.VARCHAR(length=7), nullable=False),
    sa.Column('clothing_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('clothing_color', sa.VARCHAR(length=7), nullable=False),
    sa.Column('has_glasses', sa.BOOLEAN(), nullable=False),
    sa.Column('glasses_color', sa.VARCHAR(length=7), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
